### ISSUE TITLE
failed image pull for 0.9.0

### ISSUE THREAD

**Issue by mac-abdon** [FairwindsOps/rbac-manager#109]
Was working on updating rbac-manager and it looks like images are failing to download. I moved back to 0.8.4 and image pull works. Is there a 0.9.0 image?

```
Back-off pulling image "quay.io/reactiveops/rbac-manager:0.9.0"
```

**Comment by lucasreed** [comment]
Hello! Thanks for bringing this up. That release was tagged `v0.9.0` so you'll want to add a `v` to the beginning of the image tag. This is a departure from our previous releases and we will aim to keep those consistent (with the `v`) going forward.
