### ISSUE TITLE
Wildcard in User and Mulitple Users possible to define in rbac-manager

### ISSUE THREAD

**Issue by VarunTyagi86** [FairwindsOps/rbac-manager#112]
**Case 1** - My requirement is as soon as I add a user in my EKS cluster under aws-auth config map, it should get access to view role without me to add a user in RBAC definition YAML file. Like below is something which will work wherein under I need to add User every time, a new User is added but it is not possible to define wildcard * under User so that I don't have to edit the rbac-definition YAML file ?

kind: RBACDefinition
metadata:
  name: rbac-manager-mw-read
rbacBindings:
  - name: BAU-DEV-OPS-USERS-ACCESS
    subjects:
      - kind: User
        name: *
    roleBindings:
      - clusterRole: view
        namespaceSelector:
          matchLabels:
           access: mw-global-read  
 

**Case2** - Can we add multiple Users under one Kind User? Like shown below

kind: RBACDefinition
metadata:
  name: rbac-manager-mw-read
rbacBindings:
  - name: BAU-DEV-OPS-USERS-ACCESS
    subjects:
      **- kind: User
        name: user1
        name: user2
        name: user3**
    roleBindings:
      - clusterRole: view
        namespaceSelector:
          matchLabels:
           access: common

**Comment by sudermanjr** [comment]
These things are not possible, but I believe you can solve both of them with an existing pattern

Kubernetes RBAC supports the use of `groups` which would allow you to do what you want. You can use the group as the subject in the clusterrolebinding, and then define those users as being in that group. aws-iam-authenticator supports adding the users to the group (which is what EKS does).

**Comment by VarunTyagi86** [comment]
Thank you . That helps !!
