### ISSUE TITLE
support for google groups

### ISSUE THREAD

**Issue by pankajmt** [FairwindsOps/rbac-manager#117]
are there any plans to enhance this to resolve google groups to the members? so when you search for rob in the examples at https://medium.com/uptime-99/making-sense-of-kubernetes-rbac-and-iam-roles-on-gke-914131b01922, it also resolves the google groups to search for user rob?

**Comment by sudermanjr** [comment]
@pankajmt Thanks for asking!

We do not currently have any plans to do so.  I do think we would be open to an external PR for this, so I will mark it as an enhancement in case anyone wants to pick it up.

**Comment by pankajmt** [comment]
I cant remember now, but yeah, whichever is involved with looking at google groups ...
