### ISSUE TITLE
Update CRD to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/rbac-manager#135]
The CRD version that rbac-manager uses (apiextensions.k8s.io/v1beta1) will be removed in Kubernetes 1.19.0, and is marked as deprecated in 1.16.0. We need to update this and investigate the upgrade path for existing users.

**Comment by sudermanjr** [comment]
We will also need to update the chart when this happens - see https://github.com/FairwindsOps/charts/issues/284

**Comment by wizard580** [comment]
Tbh I planned to use this rbac-manager, but since it doesn't support k8s v1.16+ (deprecated API versions) I'll wait if this will change.
Any plans on fixing this issue?

**Comment by sudermanjr** [comment]
The apiextensions/v1beta1 CRD does work in 1.16, it is not removed until 1.19.  We are hoping to work on this quarter, but it may not happen until next quarter.

**Comment by AshutoshNirkhe** [comment]
Hi @sudermanjr we are using rbac-manager v1.3.0 and planning to upgrade to latest v1.5.6 while upgrading k8s to v1.16 in coming weeks. 
RE your comment at https://github.com/FairwindsOps/charts/pull/285#issuecomment-621968888 , even if apiextensions/v1beta1 CRD works in k8s 1.16 , if we don't update the api versions in helm chart, subsequent helm upgrades will fail (as k8s will auto migrate CRD version to apiextensions.k8s.io/v1) right ?

**Comment by sudermanjr** [comment]
> subsequent helm upgrades will fail (as k8s will auto migrate CRD version to apiextensions.k8s.io/v1) right ?

No, that is not correct. Since apiextensions/v1beta1 is not actually removed from the API in 1.16, you can continue to deploy it. 

api conversion isn't a "one time" thing. It's a concept that allows the apiserver to convert between compatible versions at any time.

**Comment by sudermanjr** [comment]
For more information on how deprecation/remove and conversion work, there's some good info in this article https://www.fairwinds.com/blog/kubernetes-easily-find-deprecated-api-versions-with-pluto

**Comment by wizard580** [comment]
TBH I don't think that no one knows how to enable (bring deprecated back) APIs. But 'our project works only with old API' is something wrong.

**Comment by rbren** [comment]
Just to recap:
* rbac-manager will continue to work as-is until Kubernetes 1.19
* we are currently working to support 1.19+, and expect this to be ready before the end of the year, if not this quarter

**Comment by AshutoshNirkhe** [comment]
Thanks @sudermanjr @rbren for the explanation/confirmation!

**Comment by lucasreed** [comment]
This [chart change](https://github.com/FairwindsOps/charts/pull/385) will make the change for those that install with our helm chart.

#156 will update the deploy manifests in this repo.
