### ISSUE TITLE
Error while installing rbac-manager using helm

### ISSUE THREAD

**Issue by VarunTyagi86** [FairwindsOps/rbac-manager#144]
We have mistakenly delete namespace where rbac-manager is installed which delete all pods. Now when i am trying to install rbac-manager using helm chart it is throwing below error.

helm install rbac-manager ./rbac-manager --namespace rbac-manager
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: rbac-manager, existing_kind: rbac.authorization.k8s.io/v1beta1, Kind=ClusterRole, new_kind: rbac.authorization.k8s.io/v1beta1, Kind=ClusterRole

**Comment by rbren** [comment]
Hi Varun,

You can try `kubectl delete clusterrole rbac-manager` and `kubectl delete clusterrolebinding rbac-manager`. That should clean everything up

**Comment by VarunTyagi86** [comment]
Thank you that helped.
