### ISSUE TITLE
Warning with too old resource version coming in RBAC-MANAGER logs

### ISSUE THREAD

**Issue by VarunTyagi86** [FairwindsOps/rbac-manager#183]
Hello Team Rbac-Manager,

We are using rbac-manager v 0.9.4 and EKS version v1.17.12 and in  rbac-manager we can see below warnings, how can we resolve these warnings. Although these are not causing restarts but we do not want these warning as well .

Please suggest how to resolve these.

W0108 02:41:34.956709       1 reflector.go:270] pkg/mod/k8s.io/client-go@v0.0.0-20181213151034-8d9ed539ba31/tools/cache/reflector.go:95: watch of *v1beta1.RBACDefinition ended with: too old resource version: 34835266 (34937795)
W0108 05:22:04.417210       1 reflector.go:270] pkg/mod/k8s.io/client-go@v0.0.0-20181213151034-8d9ed539ba31/tools/cache/reflector.go:95: watch of *v1beta1.RBACDefinition ended with: too old resource version: 34937795 (34982996)

**Comment by lucasreed** [comment]
👋 Hello @VarunTyagi86, thanks for the report. Is this persistent or intermittent? The log message timestamp suggests that it is intermittent. This is a message from the kubernetes library that just means the watch has expired and needed to restart watching. There shouldn't be cause for concern for this I don't think.

**Comment by VarunTyagi86** [comment]
ok, they comes 4-5 times every day. Is there way we can fix them ?

**Comment by lucasreed** [comment]
There isn't anything to fix that I'm aware of. It's simply a warning message.
