### ISSUE TITLE
Enabling Pod security policies for rbac-manager

### ISSUE THREAD

**Issue by rramadoss4** [FairwindsOps/rbac-manager#194]
We have a security rule to disable the high privileged pod security policy that is enabled by default in EKS cluster.

Without psp, rbacmanager throws below error,
`add-ons       0s          Warning   FailedCreate        replicaset/rbac-manager-6754cdc49b         Error creating: pods "rbac-manager-6754cdc49b-" is forbidden: unable to validate against any pod security policy: []
`

What is the psp that can be used for rbac-manager?

**Comment by sudermanjr** [comment]
Correct me if I am wrong, but pod security policies are maintained by the administrators of the cluster, so you will have use one that is available in your cluster. In addition, the ability for a service account to use that policy is also controlled by cluster administrators.


If you are wondering about what capabilities and such rbac-manager needs, it should not need any. The default helm chart shows how we normally deploy it:

https://github.com/FairwindsOps/charts/blob/e846e49c383d307584591756e499af5885513377/stable/rbac-manager/templates/deployment.yaml#L57-L64

**Comment by rramadoss4** [comment]
I have created a psp with the list of permissions given in the security context of this chart..And it works fine.Thanks..
