### ISSUE TITLE
Installing RBACManager with Helm

### ISSUE THREAD

**Issue by lduparc** [FairwindsOps/rbac-manager#205]
Hi,

Trying to install RBACManager using Helm 3 (v3.5.2)
I encouter an issue because of rbac-manager chart is not existing (even after helm repo update)

```
helm repo add fairwinds-stable https://charts.fairwinds.com/stable
helm repo update
helm upgrade --install fairwinds-stable/rbac-manager rbac-manager --namespace rbac-manager --create-namespace
```

`Error: failed to download "rbac-manager" (hint: running 'helm repo update' may help)`

Any idea how to fix it ?

Thanks

**Comment by rbren** [comment]
Thanks for reaching out!

Looks like there's a typo in our install instructions ([fix here](https://github.com/FairwindsOps/rbac-manager/pull/206))

Here's the command you need:
```
helm upgrade --install rbac-manager fairwinds-stable/rbac-manager --namespace rbac-manager --create-namespace
```

**Comment by lduparc** [comment]
Oh yes, I didn't see it. 

Thanks
