### ISSUE TITLE
Ability to add labels on created resources

### ISSUE THREAD

**Issue by antoineozenne** [FairwindsOps/rbac-manager#237]
Is it possible to provide the ability to add custom labels to all created resources ? Some security requirements may require the presence of certain labels. This could be great when using `RBACDefinition` in helm charts too.
If not, is it at least possible to set the same labels as `RBACDefinition` to all resources ?

**Comment by sudermanjr** [comment]
Neither of those are possible right now, but that would be a very nice feature I think.

**Comment by eloo** [comment]
hi, i would also like to have labels on the created bindings so i can easily find specific role bindings managed by rbac-manager
for example together with kyverno to apply specific rules to these rolebindings
