### ISSUE TITLE
permission issue while deploying on GKE cluster

### ISSUE THREAD

**Issue by aqibfayyaz** [FairwindsOps/rbac-manager#259]
Hi, i am trying to deploy prefect-agent on kubernetes using skaffold.yaml . when i direcly run kubectl apply to deploy in terminal it works but when i use skaffold. yaml buid fails with the following mesage 
**Starting deploy...
 - deployment.apps/prefect-agent configured
 - Error from server (Forbidden): error when applying patch:
 - {"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"rbac.authorization.k8s.io/v1\",\"kind\":\"Role\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/managed-by\":\"skaffold\",\"skaffold.dev/run-id\":\"49c6ba62-f318-4aa7-947b-dc908428a0b9\"},\"name\":\"prefect-agent-rbac\",\"namespace\":\"default\"},\"rules\":[{\"apiGroups\":[\"batch\",\"extensions\"],\"resources\":[\"jobs\"],\"verbs\":[\"*\"]},{\"apiGroups\":[\"\"],\"resources\":[\"events\",\"pods\"],\"verbs\":[\"*\"]}]}\n"},"labels":{"app.kubernetes.io/managed-by":"skaffold","skaffold.dev/run-id":"49c6ba62-f318-4aa7-947b-dc908428a0b9"}}}
 - to:
 - Resource: "rbac.authorization.k8s.io/v1, Resource=roles", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=Role"
 - Name: "prefect-agent-rbac", Namespace: "default"
 - for: "STDIN": roles.rbac.authorization.k8s.io "prefect-agent-rbac" is forbidden: User "882602319443@cloudbuild.gserviceaccount.com" cannot patch resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "default": requires one of ["container.roles.update"] permission(s).
 - Error from server (Forbidden): error when applying patch:
 - {"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"rbac.authorization.k8s.io/v1\",\"kind\":\"RoleBinding\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/managed-by\":\"skaffold\",\"skaffold.dev/run-id\":\"49c6ba62-f318-4aa7-947b-dc908428a0b9\"},\"name\":\"prefect-agent-rbac\",\"namespace\":\"default\"},\"roleRef\":{\"apiGroup\":\"rbac.authorization.k8s.io\",\"kind\":\"Role\",\"name\":\"prefect-agent-rbac\"},\"subjects\":[{\"kind\":\"ServiceAccount\",\"name\":\"default\"}]}\n"},"labels":{"app.kubernetes.io/managed-by":"skaffold","skaffold.dev/run-id":"49c6ba62-f318-4aa7-947b-dc908428a0b9"}}}
 - to:
 - Resource: "rbac.authorization.k8s.io/v1, Resource=rolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=RoleBinding"
 - Name: "prefect-agent-rbac", Namespace: "default"
 - for: "STDIN": rolebindings.rbac.authorization.k8s.io "prefect-agent-rbac" is forbidden: User "882602319443@cloudbuild.gserviceaccount.com" cannot patch resource "rolebindings" in API group "rbac.authorization.k8s.io" in the namespace "default": requires one of ["container.roleBindings.update"] permission(s).
kubectl apply: exit status 1**

below is my prefect-agent.yaml file related to rbac
**---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-agent-rbac
  namespace: default
rules:
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - events
  - pods
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-agent-rbac
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefect-agent-rbac
subjects:
- kind: ServiceAccount
  name: default**

**Comment by lucasreed** [comment]
👋 Hello @aqibfayyaz, I think you may have opened this Issue in the incorrect repository. I'm not sure what prefect-agent is, but it's not something rbac-manager installs.
