### ISSUE TITLE
Can rbac-manager support debug log

### ISSUE THREAD

**Issue by ilanni2460** [FairwindsOps/rbac-manager#260]
Can rbac-manager support debug log

**Comment by sudermanjr** [comment]
Looks like according to `rbac-manager --help` you can use the `-log-level=debug` flag to enable debug logging.

**Comment by ilanni2460** [comment]
@sudermanjr 
How does deployment modify the log level by passing parameters?

**Comment by sudermanjr** [comment]
If I understand your question correctly, I would need to know how you are installing rbac-manager

**Comment by sudermanjr** [comment]
You can now install with helm and set these values to get debug logging

```
extraArgs:
  log-level: DEBUG
```
