### ISSUE TITLE
Cannot install rbac-manager using Helm and RBACDefinition with Terraform

### ISSUE THREAD

**Issue by MarkAndersonTrocme** [FairwindsOps/rbac-manager#269]
**Is your feature request related to a problem? Please describe.**
Do to Terraform not handling CRDs and CRs very well yet:
-  https://github.com/hashicorp/terraform-provider-kubernetes/issues/1583 
- https://github.com/hashicorp/terraform-provider-kubernetes/issues/1367

when you try to install the helm release with Terraform for rbac-manager and also apply a CR `RBACDefinition` you get:

```
│ Error: Failed to determine GroupVersionResource for manifest
│
│   with module.addons.module.rbac_manager.module.helm_chart.kubernetes_manifest.this,
│   on addons/rbac_manager/helm_chart/main.tf line 15, in resource "kubernetes_manifest" "this":
│   15: resource "kubernetes_manifest" "this" {
│
│ no matches for kind "RBACDefinition" in group "rbacmanager.reactiveops.io"
```

using this Terraform code:

```
resource "kubernetes_namespace" "this" {
  metadata {
    name = local.namespace
  }
}

resource "helm_release" "this" {
  name       = local.name
  repository = local.chart
  chart      = local.name
  version    = local.chart_version
  namespace  = kubernetes_namespace.this.metadata.0.name
}

resource "kubernetes_manifest" "this" {
  manifest = yamldecode(templatefile("${path.module}/rbac.template.yaml", {
    NAMESPACE = kubernetes_namespace.this.metadata.0.name
  }))

  depends_on = [
    helm_release.this
  ]
}
```

**Describe the solution you'd like**
It would be great if we could define a full `RBACDefinition` in the `values.yaml` of the helm chart for rbac-manager. 

**Describe alternatives you've considered**
An alternative is to deploy my own helm chart with the RBACDefinition and install that using Terraform, however it is quit a bit of overhead and not super clean IMO.

**Additional context**

**Comment by MarkAndersonTrocme** [comment]
Ah yeah the kubectl provider seems to work perfectly. I was using the [official k8s](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest) one with the `kubernetes_manifest` resource and it was failing but the kubectl provider seems 👌 

Thanks!

**Comment by sudermanjr** [comment]
Awesome! Thanks for updating!
