### ISSUE TITLE
EKS upgrade to 1.22

### ISSUE THREAD

**Issue by VarunTyagi86** [FairwindsOps/rbac-manager#298]
Hello Team RBAC Manager,

We are using EKS and currently testing the upgrade from version 1.21 to 1.22. As with Kubernetes version 1.22 few beta API version has changed, are there any changes in API version for RBAC Manager or anything else that needs to be taken care with Kubernetes 1.22 ?

**Comment by sudermanjr** [comment]
Rbac-manager has been updated to use the `rbac.authorization.k8s.io/v1`, so as long as you are up to date on rbac-manager, the upgrade should be fine.

As always, we recommend you verify this on a non-production cluster.

**Comment by VarunTyagi86** [comment]
We are using apiVersion as rbacmanager.reactiveops.io/v1beta1 , do with Kubernetes v 1.22 we have to update to rbac.authorization.k8s.io/v1 or we can continue to use rbacmanager.reactiveops.io/v1beta1 ?

**Comment by VarunTyagi86** [comment]
@sudermanjr  - Could you please let me know on this, so that we can take action accordingly.

**Comment by vishwakhrushi** [comment]
I'm facing the same issue on EKS v1.22, I'm using helm chart  version rbac-manager -1.11.1 and rbac-manager v1.1.2. I also changed the "RBACDefintion" object apiVersion to "rbacmanager.reactiveops.io/v1". Getting below error:

> `error: unable to recognize "rbac-definition.yaml": no matches for kind "RBACDefinition" in version "rbacmanager.reactiveops.io/v1"`

Also tried with kind "RBACDefinition" in version "rbacmanager.reactiveops.io/v1beta1". Getting below error:

> `error: error validating "rbac-definition.yaml": error validating data: [ValidationError(RBACDefinition.rbacBindings[2].clusterRoleBindings[0]): unknown field "namespaceSelector" in io.reactiveops.rbacmanager.v1beta1.RBACDefinition.rbacBindings.clusterRoleBindings, ValidationError(RBACDefinition.rbacBindings[3].clusterRoleBindings[0]): unknown field "namespaceSelector" in io.reactiveops.rbacmanager.v1beta1.RBACDefinition.rbacBindings.clusterRoleBindings]; if you choose to ignore these errors, turn validation off with --validate=false`
