### ISSUE TITLE
if startup is slow a warning/error occurs: [controller-runtime] log.SetLogger(...) was never called

### ISSUE THREAD

**Issue by Sven1410** [FairwindsOps/rbac-manager#420]
### What happened?

We run a setup with 43 namespaces and 10 role bindings per namespace.
During startup of rbac-manager the _"Reconciling ... namespace for ...-access" messages are written - this takes more than 30 seconds. After 30 seconds this warning/error occurs:

```
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
goroutine 88 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/log/log.go:59 +0xbd
sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithValues(0xc000118ac0, {0xc000626a80, 0x6, 0x6})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/log/deleg.go:168 +0x54
github.com/go-logr/logr.Logger.WithValues(...)
	/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:323
sigs.k8s.io/controller-runtime/pkg/controller.NewUnmanaged.func1(0xc00051e240)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/controller/controller.go:121 +0x1f6
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000369040, {0x1c78dd8, 0xc0004e2cd0}, {0x1890880?, 0xc00058e960?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:305 +0x18b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000369040, {0x1c78dd8, 0xc0004e2cd0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222 +0x587
```

I can prevent this if I set:

```
resources:
  limits:
    cpu: 500m
```
(than startup is much faster - no error/warning)

but I think this can be easily avoided if _SetLogger()_ is called earlier (?)

### What did you expect to happen?

no warning/error occurs 

### How can we reproduce this?

use many namespaces and many role bindings so that startup takes more than 30 seconds

### Version

version: 1.17.4 appVersion: 1.6.4

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Interesting. I don't actually think we call SetLogger ourselves in the rbac-manager code, but I haven't evaluated logging in a bit. 

Given that increasing the CPU limit fixes the issue, I would imagine that CPU throttling is causing something in rbac-manager to fail.

**Comment by sudermanjr** [comment]
The only meaningful changes since 1.5 are updates to dependencies, which likely means this is just an issue with controller-runtime being throttled. 10m is pretty darn small, especially for any controller watching for k8s resources.

**Comment by mauxas** [comment]
Hey i am getting the same issue from v1.6.0 and the resources doesn't help [source of issue:](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/log) 
"If SetLogger is not called within the first 30 seconds of a binaries lifetime, it will get set to a NullLogSink"

**Comment by mauxas** [comment]
Hey @sudermanjr is it possible to add this one line? I can't reopen this issue :(
