### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by oxyno-zeta** [FairwindsOps/rbac-manager#58]
# Bug

## Description
I tried to deploy this project on my Kubernetes cluster and I can see a memory leak on the latest version (0.7.0). Each 2 minutes, the rbac-manager container take around 6Mb more of RAM.

## Context
Version: 0.7.0
Log:
```
time="2019-07-10T14:30:57Z" level=info msg=----------------------------------
time="2019-07-10T14:30:57Z" level=info msg="rbac-manager 0.7.0 running"
time="2019-07-10T14:30:57Z" level=info msg=----------------------------------
time="2019-07-10T14:30:57Z" level=debug msg="Setting up client for manager"
time="2019-07-10T14:30:57Z" level=debug msg="Setting up manager"
time="2019-07-10T14:30:57Z" level=info msg="Registering components"
time="2019-07-10T14:30:57Z" level=debug msg="Setting up scheme"
time="2019-07-10T14:30:57Z" level=debug msg="Setting up controller"
time="2019-07-10T14:30:57Z" level=info msg="Watching resources related to RBAC Definitions"
time="2019-07-10T14:30:57Z" level=info msg="Watching RBAC Definitions"
time="2019-07-10T14:30:58Z" level=info msg="Reconciling RBACDefinition rbac-definition"
time="2019-07-10T14:30:58Z" level=debug msg="Cluster Role Binding already exists rbac-definition-xxx"
time="2019-07-10T14:30:58Z" level=debug msg="Matches requested Cluster Role Binding: rbac-definition-xxx"
```
RBACDefinition Kind:
```
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  creationTimestamp: 2019-07-10T14:00:33Z
  generation: 1
  labels:
    app.kubernetes.io/instance: rbac-definition
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: rbac-definition
    helm.sh/chart: rbac-definition-0.1.0
  name: rbac-definition
  resourceVersion: "39790"
  selfLink: /apis/rbacmanager.reactiveops.io/v1beta1/rbacdefinitions/rbac-definition
  uid: 1580e73a-a31b-11e9-b0a7-0e03d92c217e
rbacBindings:
- clusterRoleBindings:
  - clusterRole: cluster-admin
  name: xxx
  subjects:
  - kind: Group
    name: admin
```

## Expected behaviour:
Memory should stay at same level in time if nothing change in cluster.

Thanks !

**Comment by sudermanjr** [comment]
@oxyno-zeta Thanks for reporting this.  I'll try to take a look sometime this week.  My gut says it has to do with the new reconciliation features that were added recently.  If you have a chance, could you see if this happens in version 0.6.1 of rbac-manager?

**Comment by oxyno-zeta** [comment]
Ok I found why this appears.

I have tested with the 0.6.1 and the problem was still the same.

After a moment, I realized that it was the liveness probe ! This one was running rbac-manager at each check. That creates the memory leak (and probably other problems :) ).
I made a pull request to fix this.

Another question: 
Why this readiness/liveness exists ? As the container entrypoint is rbac-manager itself, if it crash, the container will exit. I don't see how this can be interesting, can you explain to me ?

**Comment by sudermanjr** [comment]
Thanks for catching that!  

The liveness/readiness are a tricky one in this case.  Normally it is our practice to have them on all containers, but it does seem a bit superfluous here.  The only thing this might catch is a very unlikely edge case where the container doesn't actually crash, but the rbac-manager process isn't working properly.  This particular probe is probably ineffective at this and there's probably a better way to do it.
