### ISSUE TITLE
Investigate AKS/EKS compatibility

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/rbac-manager#64]

**Comment by mdaguete** [comment]
Hi @bobby-brennan,

Currently I'm testing rbac-manager on AKS without problems, so feel free to ask.

Thanks.

**Comment by bobby-brennan** [comment]
That's great! Thanks for the info.

**Comment by sudermanjr** [comment]
EKS and AKS seem to have no obvious issues right now. I will close this and we can open any specific bugs we find going forward.
