### ISSUE TITLE
v0.8.0: manifest references v0.7.0, also liveness broken in v0.8.0

### ISSUE THREAD

**Issue by drewboswell** [FairwindsOps/rbac-manager#68]
When 
- upgrading to version v0.8.0
 - overriding the base manifest deploy file with 0.8.0. (still references 0.7.0)

The liveness probes fail due to "sh" binary missing.

**Comment by sudermanjr** [comment]
@drewboswell Thanks for bringing this to our attention.  I think the move to using the scratch docker image probably broke the probes.  We have had some discussion about probes in the past, and it might make sense in this particular case to remove them.  I'll put something together later today.
